In [1]:
import pandas as pd

import plotly.express as px

import numpy as np

In [3]:
df = pd.read_excel("/content/dataset_accidentes.xlsx")

In [5]:
df

,SEDE,SEDE DE DIVISIÓN PER.,GERENCIA DE TRABAJO,ÁREA DE TRABAJO,PUESTO DE\n TRABAJO,TURNO,HORAS MENSUAL,SITUACIÓN,TIPO DE EVENTO,FECHA DE OCURRENCIA DEL ACCIDENTE,GRAVEDAD DEL ACCIDENTE DE TRABAJO,TIPO DE ACCIDENTE,CASOS BIOLÓGICOS \n(MALAS DISPOSICIONES/SEGREGACIONES POR INSTRUMENTOS PUNZOCORTANTES),AGENTE CAUSANTE,CONDICIÓN INSEGURA,ACTO INSEGURO,SOLO ACCIDENTES BIOLÓGICOS NOTIFICACIÓN A UPCI,OBSERVACIÓN,PARTE DEL CUERPO LESIONADA,CAUSA RAIZ
0,LIMA,ADMINISTRATIVO,GERENCIA DE OPERACIONES,INGENIERIA CLINICA,SUP. DE MANTENIMIENTO EN INGENERIA CLINI,Diurno,240,CESADO,Accidente,2024-01-02,ACCIDENTE INCAPACITANTE,CORTES,NaN,PANEL DE VIDRIO,FALTA DE MANTENIMIENTO EN PUERTA DE VITRINA,VELOCIDAD INADECUADA AL REALIZAR TAREA,NaN,NaN,DEDO PULGAR MANO IZQUIERDA,No se realizó mantenimiento de las puertas de ...
1,LIMA,HOSPITALARIO,GERENCIA DE OPERACIONES,EMERGENCIA ADULTO,ENFERMERO (A),Diurno,150,ACTIVO,Accidente,2024-01-05,ACCIDENTE LEVE,BIOLÓGICO,NO,AGUJA,NO SE IDENTIFICÓ,APLICAR INYECCION A PACIENTE PARADO,SI,No tiene DM,PIERNA DERECHA,No se aplicaron buenas prácticas para aplicaci...
2,LIMA,HOSPITALARIO,GERENCIA DE OPERACIONES,EMERGENCIA ADULTO,TECNICO (A) DE ENFERMERIA,Diurno,150,ACTIVO,Accidente,2024-01-09,ACCIDENTE INCAPACITANTE,GOLPES,NaN,ALTURA INADECUADA PARA ALMACENAR OBJETOS,FALTA DE ORDEN: CAJAS AMONTONADAS UNA SOBRE OTRA,ALMACENAR OBJETOS DE MANERA INCORRECTA,NaN,NaN,PARTE FRONTAL DERECHA CABEZA,Apilamiento inadecuado de cajas
3,EXTRAMURAL,AMBULATORIO,DIRECCION MEDICA CORPORATIVA,LABORATORIO CLINICO,TECNICO (A) DE LABORATORIO,Diurno,150,CESADO,Accidente,2024-01-12,ACCIDENTE LEVE,BIOLÓGICO,NO,MORDEDURA DE CAN,PRESENCIA DE CAN EN DOMICILIO,NO SE IDENTIFICÓ,SI,No tiene DM,CADERA IZQUIERDA,Condiciones inadecuadas para atención en domic...
4,EXTRAMURAL,AMBULATORIO,DIRECCION MEDICA CORPORATIVA,LABORATORIO CLINICO,TECNICO (A) DE LABORATORIO,Diurno,150,ACTIVO,Accidente,2024-01-13,ACCIDENTE LEVE,BIOLÓGICO,NO,AGUJA,NO SE IDENTIFICÓ,DISTRACCIÓN AL REALIZAR LA TAREA,SI,No tiene DM,DEDO INDICE DE LA MANO IZQUIERDA,Exceso de confianza
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,SAN BORJA,HOSPITALARIO,DIRECCION MEDICA CORPORATIVA,LABORATORIO CLINICO,TECNICO (A) DE LABORATORIO,Diurno,180,ACTIVO,Accidente,2026-05-14,ACCIDENTE LEVE,CAÍDAS,NO,PRESENCIA DE SILLA EN PASILLO,FALTA DE ORDEN,NaN,NaN,No tiene DM,AMBAS RODILLAS\nBRAZO DERECHO,NaN
255,SAN BORJA,HOSPITALARIO,GERENCIA DE OPERACIONES,SALA DE OPERACIONES,TECNICO (A) DE ENFERMERIA,Diurno,150,ACTIVO,Accidente,2026-05-19,ACCIDENTE INCAPACITANTE,CAÍDAS,NO,PISO RESBALOSO,NaN,NaN,NaN,Si tiene DM,MEJILLA DERECHA\nAMBAS RODILLAS\nBRAZO DERECHO,NaN
256,LIMA,AMBULATORIO,GERENCIA DE OPERACIONES,CONSULTORIO CLINICO,TECNICO (A) DE ENFERMERIA,Diurno,150,ACTIVO,Accidente,2026-05-23,ACCIDENTE INCAPACITANTE,CAÍDAS,NO,PISO HUMEDO,NaN,REALIZAR ACTIVIDADES SIN REVISAR ENTORNO,NaN,Si tiene DM,BRAZO IZQUIERDO\nMUÑECA IZQUIERDA,NaN
257,SAN BORJA,AMBULATORIO,DIRECCION MEDICA CORPORATIVA,FARMACIA AMBULATORIA,TECNICO (A) DE FARMACIA,Diurno,150,CESADO,Accidente,2026-06-05,ACCIDENTE INCAPACITANTE,CAÍDAS,NO,AUSENCIA DE VISIBILIDAD AL TRASLADAR CAJA DE M...,NaN,DESCENDER POR ESCALERAS TRANSPORTANDO MATERIAL...,NaN,Si tiene DM,PIE IZQUIERDO,NaN
258,LIMA,HOSPITALARIO,DIRECCION MEDICA CORPORATIVA,FARMACIA HOSPITALARIA,TECNICO (A) DE FARMACIA,Diurno,180,ACTIVO,Accidente,2026-06-04,ACCIDENTE INCAPACITANTE,GOLPES,NO,AUSENCIA DE VISIBILIDAD AL TRASLADAR CAJA COCH...,NaN,REALIZAR ACTIVIDADES SIN REVISAR ENTORNO,NaN,Si tiene DM,TOBILLO IZQUIERDO,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 259 entries, 0 to 258
Data columns (total 20 columns):
 #   Column                                                                                 Non-Null Count  Dtype
---  ------                                                                                 --------------  -----
 0   SEDE                                                                                   259 non-null    object
 1   SEDE DE DIVISIÓN PER.                                                                  259 non-null    object
 2   GERENCIA DE TRABAJO                                                                    259 non-null    object
 3   ÁREA DE TRABAJO                                                                        259 non-null    object
 4   PUESTO DE
 TRABAJO                                                                     259 non-null    object
 5   TURNO                                                                                  259 non-null    object
 6   HORAS MENSUAL                                                                          259 non-null    int64
 7   SITUACIÓN                                                                              259 non-null    object
 8   TIPO DE EVENTO                                                                         259 non-null    object
 9   FECHA DE OCURRENCIA DEL ACCIDENTE                                                      259 non-null    datetime64[ns]
 10  GRAVEDAD DEL ACCIDENTE DE TRABAJO                                                      259 non-null    object
 11  TIPO DE ACCIDENTE                                                                      259 non-null    object
 12  CASOS BIOLÓGICOS
(MALAS DISPOSICIONES/SEGREGACIONES POR INSTRUMENTOS PUNZOCORTANTES)  235 non-null    object
 13  AGENTE CAUSANTE                                                                        259 non-null    object
 14  CONDICIÓN INSEGURA                                                                     251 non-null    object
 15  ACTO INSEGURO                                                                          249 non-null    object
 16  SOLO ACCIDENTES BIOLÓGICOS NOTIFICACIÓN A UPCI                                         100 non-null    object
 17  OBSERVACIÓN                                                                            153 non-null    object
 18  PARTE DEL CUERPO LESIONADA                                                             254 non-null    object
 19  CAUSA RAIZ                                                                             172 non-null    object
dtypes: datetime64[ns](1), int64(1), object(18)
memory usage: 40.6+ KB

In [7]:
df.head()

,SEDE,SEDE DE DIVISIÓN PER.,GERENCIA DE TRABAJO,ÁREA DE TRABAJO,PUESTO DE\n TRABAJO,TURNO,HORAS MENSUAL,SITUACIÓN,TIPO DE EVENTO,FECHA DE OCURRENCIA DEL ACCIDENTE,GRAVEDAD DEL ACCIDENTE DE TRABAJO,TIPO DE ACCIDENTE,CASOS BIOLÓGICOS \n(MALAS DISPOSICIONES/SEGREGACIONES POR INSTRUMENTOS PUNZOCORTANTES),AGENTE CAUSANTE,CONDICIÓN INSEGURA,ACTO INSEGURO,SOLO ACCIDENTES BIOLÓGICOS NOTIFICACIÓN A UPCI,OBSERVACIÓN,PARTE DEL CUERPO LESIONADA,CAUSA RAIZ
0,LIMA,ADMINISTRATIVO,GERENCIA DE OPERACIONES,INGENIERIA CLINICA,SUP. DE MANTENIMIENTO EN INGENERIA CLINI,Diurno,240,CESADO,Accidente,2024-01-02,ACCIDENTE INCAPACITANTE,CORTES,NaN,PANEL DE VIDRIO,FALTA DE MANTENIMIENTO EN PUERTA DE VITRINA,VELOCIDAD INADECUADA AL REALIZAR TAREA,NaN,NaN,DEDO PULGAR MANO IZQUIERDA,No se realizó mantenimiento de las puertas de ...
1,LIMA,HOSPITALARIO,GERENCIA DE OPERACIONES,EMERGENCIA ADULTO,ENFERMERO (A),Diurno,150,ACTIVO,Accidente,2024-01-05,ACCIDENTE LEVE,BIOLÓGICO,NO,AGUJA,NO SE IDENTIFICÓ,APLICAR INYECCION A PACIENTE PARADO,SI,No tiene DM,PIERNA DERECHA,No se aplicaron buenas prácticas para aplicaci...
2,LIMA,HOSPITALARIO,GERENCIA DE OPERACIONES,EMERGENCIA ADULTO,TECNICO (A) DE ENFERMERIA,Diurno,150,ACTIVO,Accidente,2024-01-09,ACCIDENTE INCAPACITANTE,GOLPES,NaN,ALTURA INADECUADA PARA ALMACENAR OBJETOS,FALTA DE ORDEN: CAJAS AMONTONADAS UNA SOBRE OTRA,ALMACENAR OBJETOS DE MANERA INCORRECTA,NaN,NaN,PARTE FRONTAL DERECHA CABEZA,Apilamiento inadecuado de cajas
3,EXTRAMURAL,AMBULATORIO,DIRECCION MEDICA CORPORATIVA,LABORATORIO CLINICO,TECNICO (A) DE LABORATORIO,Diurno,150,CESADO,Accidente,2024-01-12,ACCIDENTE LEVE,BIOLÓGICO,NO,MORDEDURA DE CAN,PRESENCIA DE CAN EN DOMICILIO,NO SE IDENTIFICÓ,SI,No tiene DM,CADERA IZQUIERDA,Condiciones inadecuadas para atención en domic...
4,EXTRAMURAL,AMBULATORIO,DIRECCION MEDICA CORPORATIVA,LABORATORIO CLINICO,TECNICO (A) DE LABORATORIO,Diurno,150,ACTIVO,Accidente,2024-01-13,ACCIDENTE LEVE,BIOLÓGICO,NO,AGUJA,NO SE IDENTIFICÓ,DISTRACCIÓN AL REALIZAR LA TAREA,SI,No tiene DM,DEDO INDICE DE LA MANO IZQUIERDA,Exceso de confianza

In [8]:
df.tail()

,SEDE,SEDE DE DIVISIÓN PER.,GERENCIA DE TRABAJO,ÁREA DE TRABAJO,PUESTO DE\n TRABAJO,TURNO,HORAS MENSUAL,SITUACIÓN,TIPO DE EVENTO,FECHA DE OCURRENCIA DEL ACCIDENTE,GRAVEDAD DEL ACCIDENTE DE TRABAJO,TIPO DE ACCIDENTE,CASOS BIOLÓGICOS \n(MALAS DISPOSICIONES/SEGREGACIONES POR INSTRUMENTOS PUNZOCORTANTES),AGENTE CAUSANTE,CONDICIÓN INSEGURA,ACTO INSEGURO,SOLO ACCIDENTES BIOLÓGICOS NOTIFICACIÓN A UPCI,OBSERVACIÓN,PARTE DEL CUERPO LESIONADA,CAUSA RAIZ
254,SAN BORJA,HOSPITALARIO,DIRECCION MEDICA CORPORATIVA,LABORATORIO CLINICO,TECNICO (A) DE LABORATORIO,Diurno,180,ACTIVO,Accidente,2026-05-14,ACCIDENTE LEVE,CAÍDAS,NO,PRESENCIA DE SILLA EN PASILLO,FALTA DE ORDEN,NaN,NaN,No tiene DM,AMBAS RODILLAS\nBRAZO DERECHO,NaN
255,SAN BORJA,HOSPITALARIO,GERENCIA DE OPERACIONES,SALA DE OPERACIONES,TECNICO (A) DE ENFERMERIA,Diurno,150,ACTIVO,Accidente,2026-05-19,ACCIDENTE INCAPACITANTE,CAÍDAS,NO,PISO RESBALOSO,NaN,NaN,NaN,Si tiene DM,MEJILLA DERECHA\nAMBAS RODILLAS\nBRAZO DERECHO,NaN
256,LIMA,AMBULATORIO,GERENCIA DE OPERACIONES,CONSULTORIO CLINICO,TECNICO (A) DE ENFERMERIA,Diurno,150,ACTIVO,Accidente,2026-05-23,ACCIDENTE INCAPACITANTE,CAÍDAS,NO,PISO HUMEDO,NaN,REALIZAR ACTIVIDADES SIN REVISAR ENTORNO,NaN,Si tiene DM,BRAZO IZQUIERDO\nMUÑECA IZQUIERDA,NaN
257,SAN BORJA,AMBULATORIO,DIRECCION MEDICA CORPORATIVA,FARMACIA AMBULATORIA,TECNICO (A) DE FARMACIA,Diurno,150,CESADO,Accidente,2026-06-05,ACCIDENTE INCAPACITANTE,CAÍDAS,NO,AUSENCIA DE VISIBILIDAD AL TRASLADAR CAJA DE M...,NaN,DESCENDER POR ESCALERAS TRANSPORTANDO MATERIAL...,NaN,Si tiene DM,PIE IZQUIERDO,NaN
258,LIMA,HOSPITALARIO,DIRECCION MEDICA CORPORATIVA,FARMACIA HOSPITALARIA,TECNICO (A) DE FARMACIA,Diurno,180,ACTIVO,Accidente,2026-06-04,ACCIDENTE INCAPACITANTE,GOLPES,NO,AUSENCIA DE VISIBILIDAD AL TRASLADAR CAJA COCH...,NaN,REALIZAR ACTIVIDADES SIN REVISAR ENTORNO,NaN,Si tiene DM,TOBILLO IZQUIERDO,NaN

In [10]:
df.shape

(259, 20)

In [11]:
df.columns

Index(['SEDE', 'SEDE DE DIVISIÓN PER.', 'GERENCIA DE TRABAJO',
       'ÁREA DE TRABAJO', 'PUESTO DE\n TRABAJO', 'TURNO', 'HORAS MENSUAL',
       'SITUACIÓN', 'TIPO DE EVENTO', 'FECHA DE OCURRENCIA DEL ACCIDENTE',
       'GRAVEDAD DEL ACCIDENTE DE TRABAJO', 'TIPO DE ACCIDENTE ',
       'CASOS BIOLÓGICOS \n(MALAS DISPOSICIONES/SEGREGACIONES POR INSTRUMENTOS PUNZOCORTANTES)',
       'AGENTE CAUSANTE', 'CONDICIÓN INSEGURA', 'ACTO INSEGURO',
       'SOLO ACCIDENTES BIOLÓGICOS NOTIFICACIÓN A UPCI', 'OBSERVACIÓN',
       'PARTE DEL CUERPO LESIONADA', 'CAUSA RAIZ'],
      dtype='object')

In [12]:
df.dtypes

SEDE                                                                                              object
SEDE DE DIVISIÓN PER.                                                                             object
GERENCIA DE TRABAJO                                                                               object
ÁREA DE TRABAJO                                                                                   object
PUESTO DE\n TRABAJO                                                                               object
TURNO                                                                                             object
HORAS MENSUAL                                                                                      int64
SITUACIÓN                                                                                         object
TIPO DE EVENTO                                                                                    object
FECHA DE OCURRENCIA DEL ACCIDENTE                                                         datetime64[ns]
GRAVEDAD DEL ACCIDENTE DE TRABAJO                                                                 object
TIPO DE ACCIDENTE                                                                                 object
CASOS BIOLÓGICOS \n(MALAS DISPOSICIONES/SEGREGACIONES POR INSTRUMENTOS PUNZOCORTANTES)            object
AGENTE CAUSANTE                                                                                   object
CONDICIÓN INSEGURA                                                                                object
ACTO INSEGURO                                                                                     object
SOLO ACCIDENTES BIOLÓGICOS NOTIFICACIÓN A UPCI                                                    object
OBSERVACIÓN                                                                                       object
PARTE DEL CUERPO LESIONADA                                                                        object
CAUSA RAIZ                                                                                        object
dtype: object

In [13]:
df.isnull().sum()

SEDE                                                                                        0
SEDE DE DIVISIÓN PER.                                                                       0
GERENCIA DE TRABAJO                                                                         0
ÁREA DE TRABAJO                                                                             0
PUESTO DE\n TRABAJO                                                                         0
TURNO                                                                                       0
HORAS MENSUAL                                                                               0
SITUACIÓN                                                                                   0
TIPO DE EVENTO                                                                              0
FECHA DE OCURRENCIA DEL ACCIDENTE                                                           0
GRAVEDAD DEL ACCIDENTE DE TRABAJO                                                           0
TIPO DE ACCIDENTE                                                                           0
CASOS BIOLÓGICOS \n(MALAS DISPOSICIONES/SEGREGACIONES POR INSTRUMENTOS PUNZOCORTANTES)     24
AGENTE CAUSANTE                                                                             0
CONDICIÓN INSEGURA                                                                          8
ACTO INSEGURO                                                                              10
SOLO ACCIDENTES BIOLÓGICOS NOTIFICACIÓN A UPCI                                            159
OBSERVACIÓN                                                                               106
PARTE DEL CUERPO LESIONADA                                                                  5
CAUSA RAIZ                                                                                 87
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(0)

In [18]:
df.describe()

       HORAS MENSUAL FECHA DE OCURRENCIA DEL ACCIDENTE
count     259.000000                               259
mean      172.239382     2025-02-02 05:28:01.853281792
min         0.000000               2024-01-02 00:00:00
25%       150.000000               2024-05-15 12:00:00
50%       180.000000               2025-01-11 00:00:00
75%       180.000000               2025-09-27 00:00:00
max       240.000000               2026-06-05 00:00:00
std        33.518545                               NaN

In [19]:
(df == "").sum()

SEDE                                                                                      0
SEDE DE DIVISIÓN PER.                                                                     0
GERENCIA DE TRABAJO                                                                       0
ÁREA DE TRABAJO                                                                           0
PUESTO DE\n TRABAJO                                                                       0
TURNO                                                                                     0
HORAS MENSUAL                                                                             0
SITUACIÓN                                                                                 0
TIPO DE EVENTO                                                                            0
FECHA DE OCURRENCIA DEL ACCIDENTE                                                         0
GRAVEDAD DEL ACCIDENTE DE TRABAJO                                                         0
TIPO DE ACCIDENTE                                                                         0
CASOS BIOLÓGICOS \n(MALAS DISPOSICIONES/SEGREGACIONES POR INSTRUMENTOS PUNZOCORTANTES)    0
AGENTE CAUSANTE                                                                           0
CONDICIÓN INSEGURA                                                                        0
ACTO INSEGURO                                                                             0
SOLO ACCIDENTES BIOLÓGICOS NOTIFICACIÓN A UPCI                                            0
OBSERVACIÓN                                                                               0
PARTE DEL CUERPO LESIONADA                                                                0
CAUSA RAIZ                                                                                0
dtype: int64

In [20]:
df["SEDE"].unique()

array(['LIMA', 'EXTRAMURAL', 'SAN BORJA', 'SURCO', 'SAN ISIDRO',
       'LA MOLINA'], dtype=object)

In [30]:
print(df.columns.tolist())

['SEDE', 'SEDE DE DIVISIÓN PER.', 'GERENCIA DE TRABAJO', 'ÁREA DE TRABAJO', 'PUESTO DE\n TRABAJO', 'TURNO', 'HORAS MENSUAL', 'SITUACIÓN', 'TIPO DE EVENTO', 'FECHA DE OCURRENCIA DEL ACCIDENTE', 'GRAVEDAD DEL ACCIDENTE DE TRABAJO', 'TIPO DE ACCIDENTE ', 'CASOS BIOLÓGICOS \n(MALAS DISPOSICIONES/SEGREGACIONES POR INSTRUMENTOS PUNZOCORTANTES)', 'AGENTE CAUSANTE', 'CONDICIÓN INSEGURA', 'ACTO INSEGURO', 'SOLO ACCIDENTES BIOLÓGICOS NOTIFICACIÓN A UPCI', 'OBSERVACIÓN', 'PARTE DEL CUERPO LESIONADA', 'CAUSA RAIZ']

In [31]:
df["TIPO DE ACCIDENTE "].unique()

array(['CORTES', 'BIOLÓGICO', 'GOLPES', 'QUÍMICO', 'CAÍDAS',
       'EXCESO DE CONFIANZA', 'PICADURAS', 'QUEMADURA', 'ERGONÓMICO',
       'CONTUSION', ' CORTES', 'ELECTRICO', 'MECANICO', 'FISICO'],
      dtype=object)

In [32]:
print("=== Estadística descriptiva de variables numéricas ===")
df.describe()

=== Estadística descriptiva de variables numéricas ===

       HORAS MENSUAL FECHA DE OCURRENCIA DEL ACCIDENTE
count     259.000000                               259
mean      172.239382     2025-02-02 05:28:01.853281792
min         0.000000               2024-01-02 00:00:00
25%       150.000000               2024-05-15 12:00:00
50%       180.000000               2025-01-11 00:00:00
75%       180.000000               2025-09-27 00:00:00
max       240.000000               2026-06-05 00:00:00
std        33.518545                               NaN

Los registros de accidentes se concentran principalmente en el período comprendido entre 2024 y 2026, siendo el tercer cuartil una fecha correspondiente al año 2025

In [34]:
df["AÑO"] = df["FECHA DE OCURRENCIA DEL ACCIDENTE"].dt.year
df["AÑO"].value_counts()

AÑO
2024    128
2025     94
2026     37
Name: count, dtype: int64

Se aprecia que el 2024 fue el año donde hubo mayor reporte de accidentes.

In [33]:
print("=== Resumen de variables categóricas ===")
df.describe(include="object")

=== Resumen de variables categóricas ===

,SEDE,SEDE DE DIVISIÓN PER.,GERENCIA DE TRABAJO,ÁREA DE TRABAJO,PUESTO DE\n TRABAJO,TURNO,SITUACIÓN,TIPO DE EVENTO,GRAVEDAD DEL ACCIDENTE DE TRABAJO,TIPO DE ACCIDENTE,CASOS BIOLÓGICOS \n(MALAS DISPOSICIONES/SEGREGACIONES POR INSTRUMENTOS PUNZOCORTANTES),AGENTE CAUSANTE,CONDICIÓN INSEGURA,ACTO INSEGURO,SOLO ACCIDENTES BIOLÓGICOS NOTIFICACIÓN A UPCI,OBSERVACIÓN,PARTE DEL CUERPO LESIONADA,CAUSA RAIZ
count,259,259,259,259,259,259,259,259,259,259,235,259,251,249,100,153,254,172
unique,6,5,7,67,48,3,2,1,2,14,3,111,109,99,4,4,102,117
top,SAN BORJA,HOSPITALARIO,GERENCIA DE OPERACIONES,SALA DE OPERACIONES,TECNICO (A) DE ENFERMERIA,Diurno,ACTIVO,Accidente,ACCIDENTE INCAPACITANTE,BIOLÓGICO,-,AGUJA,NO SE IDENTIFICÓ,NO SE IDENTIFICÓ,SI,No tiene DM,DEDO PULGAR MANO IZQUIERDA,Pisos resbalosos
freq,140,147,166,22,85,232,170,259,142,81,112,39,112,54,74,94,18,10

La sede con mayor frecuencia de accidentes corresponde a SAN BORJA. Asimismo, el tipo de accidente más reportado fue "Biológico".

In [35]:
import plotly.express as px

In [36]:
accidentes_mes = df.groupby(df["FECHA DE OCURRENCIA DEL ACCIDENTE"].dt.to_period("M")).size().reset_index(name="Cantidad")

accidentes_mes["FECHA DE OCURRENCIA DEL ACCIDENTE"] = accidentes_mes["FECHA DE OCURRENCIA DEL ACCIDENTE"].astype(str)

fig = px.line(
    accidentes_mes,
    x="FECHA DE OCURRENCIA DEL ACCIDENTE",
    y="Cantidad",
    title="Accidentes por mes"
)

fig.show()

In [37]:
conteo = df["SEDE"].value_counts().reset_index()

conteo.columns = ["SEDE","Cantidad"]

fig = px.bar(
    conteo,
    x="SEDE",
    y="Cantidad",
    title="Cantidad de accidentes por sede"
)

fig.show()

In [39]:
conteo = df["TIPO DE ACCIDENTE "].value_counts().reset_index()

conteo.columns = ["Tipo","Cantidad"]

fig = px.pie(
    conteo,
    names="Tipo",
    values="Cantidad",
    title="Distribución por tipo de accidente"
)

fig.show()

In [41]:
fig = px.histogram(
    df,
    x="HORAS MENSUAL",
    title="Distribución de horas mensuales"
)

fig.show()

In [43]:
fig = px.box(
    df,
    y="FECHA DE OCURRENCIA DEL ACCIDENTE",
    title="Valores atípicos de fecha de ocurrencia de accidentes"
)

fig.show()

In [44]:
import duckdb

In [45]:
duckdb.sql("SELECT * FROM df LIMIT 5").df()

,SEDE,SEDE DE DIVISIÓN PER.,GERENCIA DE TRABAJO,ÁREA DE TRABAJO,PUESTO DE\n TRABAJO,TURNO,HORAS MENSUAL,SITUACIÓN,TIPO DE EVENTO,FECHA DE OCURRENCIA DEL ACCIDENTE,...,TIPO DE ACCIDENTE,CASOS BIOLÓGICOS \n(MALAS DISPOSICIONES/SEGREGACIONES POR INSTRUMENTOS PUNZOCORTANTES),AGENTE CAUSANTE,CONDICIÓN INSEGURA,ACTO INSEGURO,SOLO ACCIDENTES BIOLÓGICOS NOTIFICACIÓN A UPCI,OBSERVACIÓN,PARTE DEL CUERPO LESIONADA,CAUSA RAIZ,AÑO
0,LIMA,ADMINISTRATIVO,GERENCIA DE OPERACIONES,INGENIERIA CLINICA,SUP. DE MANTENIMIENTO EN INGENERIA CLINI,Diurno,240,CESADO,Accidente,2024-01-02,...,CORTES,None,PANEL DE VIDRIO,FALTA DE MANTENIMIENTO EN PUERTA DE VITRINA,VELOCIDAD INADECUADA AL REALIZAR TAREA,None,None,DEDO PULGAR MANO IZQUIERDA,No se realizó mantenimiento de las puertas de ...,2024
1,LIMA,HOSPITALARIO,GERENCIA DE OPERACIONES,EMERGENCIA ADULTO,ENFERMERO (A),Diurno,150,ACTIVO,Accidente,2024-01-05,...,BIOLÓGICO,NO,AGUJA,NO SE IDENTIFICÓ,APLICAR INYECCION A PACIENTE PARADO,SI,No tiene DM,PIERNA DERECHA,No se aplicaron buenas prácticas para aplicaci...,2024
2,LIMA,HOSPITALARIO,GERENCIA DE OPERACIONES,EMERGENCIA ADULTO,TECNICO (A) DE ENFERMERIA,Diurno,150,ACTIVO,Accidente,2024-01-09,...,GOLPES,None,ALTURA INADECUADA PARA ALMACENAR OBJETOS,FALTA DE ORDEN: CAJAS AMONTONADAS UNA SOBRE OTRA,ALMACENAR OBJETOS DE MANERA INCORRECTA,None,None,PARTE FRONTAL DERECHA CABEZA,Apilamiento inadecuado de cajas,2024
3,EXTRAMURAL,AMBULATORIO,DIRECCION MEDICA CORPORATIVA,LABORATORIO CLINICO,TECNICO (A) DE LABORATORIO,Diurno,150,CESADO,Accidente,2024-01-12,...,BIOLÓGICO,NO,MORDEDURA DE CAN,PRESENCIA DE CAN EN DOMICILIO,NO SE IDENTIFICÓ,SI,No tiene DM,CADERA IZQUIERDA,Condiciones inadecuadas para atención en domic...,2024
4,EXTRAMURAL,AMBULATORIO,DIRECCION MEDICA CORPORATIVA,LABORATORIO CLINICO,TECNICO (A) DE LABORATORIO,Diurno,150,ACTIVO,Accidente,2024-01-13,...,BIOLÓGICO,NO,AGUJA,NO SE IDENTIFICÓ,DISTRACCIÓN AL REALIZAR LA TAREA,SI,No tiene DM,DEDO INDICE DE LA MANO IZQUIERDA,Exceso de confianza,2024

In [46]:
duckdb.sql("""
SELECT *
FROM df
LIMIT 10
""").df()

,SEDE,SEDE DE DIVISIÓN PER.,GERENCIA DE TRABAJO,ÁREA DE TRABAJO,PUESTO DE\n TRABAJO,TURNO,HORAS MENSUAL,SITUACIÓN,TIPO DE EVENTO,FECHA DE OCURRENCIA DEL ACCIDENTE,...,TIPO DE ACCIDENTE,CASOS BIOLÓGICOS \n(MALAS DISPOSICIONES/SEGREGACIONES POR INSTRUMENTOS PUNZOCORTANTES),AGENTE CAUSANTE,CONDICIÓN INSEGURA,ACTO INSEGURO,SOLO ACCIDENTES BIOLÓGICOS NOTIFICACIÓN A UPCI,OBSERVACIÓN,PARTE DEL CUERPO LESIONADA,CAUSA RAIZ,AÑO
0,LIMA,ADMINISTRATIVO,GERENCIA DE OPERACIONES,INGENIERIA CLINICA,SUP. DE MANTENIMIENTO EN INGENERIA CLINI,Diurno,240,CESADO,Accidente,2024-01-02,...,CORTES,None,PANEL DE VIDRIO,FALTA DE MANTENIMIENTO EN PUERTA DE VITRINA,VELOCIDAD INADECUADA AL REALIZAR TAREA,None,None,DEDO PULGAR MANO IZQUIERDA,No se realizó mantenimiento de las puertas de ...,2024
1,LIMA,HOSPITALARIO,GERENCIA DE OPERACIONES,EMERGENCIA ADULTO,ENFERMERO (A),Diurno,150,ACTIVO,Accidente,2024-01-05,...,BIOLÓGICO,NO,AGUJA,NO SE IDENTIFICÓ,APLICAR INYECCION A PACIENTE PARADO,SI,No tiene DM,PIERNA DERECHA,No se aplicaron buenas prácticas para aplicaci...,2024
2,LIMA,HOSPITALARIO,GERENCIA DE OPERACIONES,EMERGENCIA ADULTO,TECNICO (A) DE ENFERMERIA,Diurno,150,ACTIVO,Accidente,2024-01-09,...,GOLPES,None,ALTURA INADECUADA PARA ALMACENAR OBJETOS,FALTA DE ORDEN: CAJAS AMONTONADAS UNA SOBRE OTRA,ALMACENAR OBJETOS DE MANERA INCORRECTA,None,None,PARTE FRONTAL DERECHA CABEZA,Apilamiento inadecuado de cajas,2024
3,EXTRAMURAL,AMBULATORIO,DIRECCION MEDICA CORPORATIVA,LABORATORIO CLINICO,TECNICO (A) DE LABORATORIO,Diurno,150,CESADO,Accidente,2024-01-12,...,BIOLÓGICO,NO,MORDEDURA DE CAN,PRESENCIA DE CAN EN DOMICILIO,NO SE IDENTIFICÓ,SI,No tiene DM,CADERA IZQUIERDA,Condiciones inadecuadas para atención en domic...,2024
4,EXTRAMURAL,AMBULATORIO,DIRECCION MEDICA CORPORATIVA,LABORATORIO CLINICO,TECNICO (A) DE LABORATORIO,Diurno,150,ACTIVO,Accidente,2024-01-13,...,BIOLÓGICO,NO,AGUJA,NO SE IDENTIFICÓ,DISTRACCIÓN AL REALIZAR LA TAREA,SI,No tiene DM,DEDO INDICE DE LA MANO IZQUIERDA,Exceso de confianza,2024
5,SAN BORJA,HOSPITALARIO,DIRECCION MEDICA CORPORATIVA,FARMACIA HOSPITALARIA,TECNICO (A) DE FARMACIA,Diurno,150,ACTIVO,Accidente,2024-01-17,...,CORTES,-,MATERIAL DE ESCRITRORIO,NO SE IDENTIFICÓ,DISTRACCIÓN AL REALIZAR LA TAREA,None,None,DEDO PULGAR MANO IZQUIERDA,Exceso de confianza,2024
6,SAN BORJA,HOSPITALARIO,GERENCIA DE OPERACIONES,UCI,TECNICO (A) DE ENFERMERIA,Diurno,150,CESADO,Accidente,2024-01-20,...,GOLPES,-,BARANDA DE ESCALERA,NO SE IDENTIFICÓ,DISTRACCIÓN AL REALIZAR LA TAREA,None,None,MUÑECA DERECHA,Exceso de confianza,2024
7,SAN BORJA,HOSPITALARIO,GERENCIA DE OPERACIONES,UCI,ENFERMERO (A),Diurno,150,ACTIVO,Accidente,2024-01-20,...,QUÍMICO,-,PRODUCTO MÉDICO,DISPOSITIVO DEFECTUOSO,FALTA DE USO DE EPP,None,None,OJO DERECHO,Falta de uso de los equipos de proteccion pers...,2024
8,SAN BORJA,HOSPITALARIO,DIRECCION MEDICA CORPORATIVA,IMÁGENES-UDIM,ENFERMERO (A),Diurno,150,ACTIVO,Accidente,2024-01-18,...,CAÍDAS,-,MESA X-HIS,EQUIPO DEFECTUOSO (COCHE DE LAPTOP),MOVILIZAR EQUIPOS DE MANERA INCORRECTA,None,None,ROSTRO,Inadecuado mantenimiento de mobiliario,2024
9,SAN BORJA,HOSPITALARIO,GERENCIA DE OPERACIONES,EMERGENCIA PEDIATRICA,TECNICO (A) DE ENFERMERIA,Diurno,180,CESADO,Accidente,2024-01-24,...,CAÍDAS,-,MOBILIARIO (SILLA DE TRABAJO),SILLA INADECUADA,REALIZAR LA TAREA DISTRAIDA,None,None,"CLAVICULA,ESPALDA Y PIERNA",Mobiliario inadecuado,2024

In [52]:
duckdb.sql("""
SELECT
    SEDE,
    COUNT(*) AS Cantidad_Accidentes
FROM df
GROUP BY SEDE
ORDER BY Cantidad_Accidentes DESC
""").df()

         SEDE  Cantidad_Accidentes
0   SAN BORJA                  140
1        LIMA                   86
2       SURCO                   17
3  SAN ISIDRO                    9
4  EXTRAMURAL                    4
5   LA MOLINA                    3

In [55]:
duckdb.sql("""
SELECT
    "TIPO DE ACCIDENTE ",
    COUNT(*) AS Cantidad
FROM df
GROUP BY "TIPO DE ACCIDENTE "
ORDER BY Cantidad DESC
""").df()

     TIPO DE ACCIDENTE   Cantidad
0             BIOLÓGICO        81
1                CAÍDAS        71
2                GOLPES        65
3                CORTES        10
4               QUÍMICO        10
5              MECANICO         7
6            ERGONÓMICO         7
7             CONTUSION         2
8             PICADURAS         1
9                CORTES         1
10               FISICO         1
11  EXCESO DE CONFIANZA         1
12            QUEMADURA         1
13            ELECTRICO         1

In [57]:
duckdb.sql("""
SELECT
AVG("HORAS MENSUAL") AS Promedio_Horas
FROM df
""").df()

   Promedio_Horas
0      172.239382

In [58]:
duckdb.sql("""
SELECT
YEAR("FECHA DE OCURRENCIA DEL ACCIDENTE") AS Año,
COUNT(*) AS Accidentes
FROM df
GROUP BY Año
ORDER BY Año
""").df()

    Año  Accidentes
0  2024         128
1  2025          94
2  2026          37

**HALLAZGOS:**
Se identificó una tendencia descendente en la cantidad de accidentes laborales registrados entre los años 2024 y 2026.
La sede San Borja presentó la mayor incidencia de accidentes dentro del conjunto de datos analizado.
El accidente biológico fue el tipo de accidente con mayor frecuencia.
Las visualizaciones desarrolladas con Plotly permitieron identificar de manera clara las tendencias y la distribución de los accidentes.
La revisión de la calidad de los datos (valores nulos, vacíos y duplicados) permitió contar con información más confiable para el análisis y la ejecución de consultas SQL.
**CONCLUSIONES: **
El desarrollo de este proyecto permitió aplicar Python, pandas, Plotly y DuckDB para analizar una base de datos de accidentes laborales de forma organizada. Asimismo, se comprobó que estas herramientas facilitan la exploración, visualización y consulta de la información, optimizando el análisis de datos y constituyendo una alternativa más eficiente que Excel para procesos repetitivos o grandes volúmenes de información.